### ISSUE TITLE
Use kebab-case

### ISSUE THREAD

**Issue by pheeria** [ayaqdop/frontend#9]
Rename all directories and files to confirm `kebab-case` style.
Please make sure that case-only changes are [noticed properly by git](https://stackoverflow.com/q/17683458).
Also, please rename files in component directories to `index.js` and `index.css`.
Example:
```
/long-component-name
    index.js
    index.css
/component
    index.js
    index.css
```

**Comment by br3akzero** [comment]
If this is still active I would love to do the prettify code and this issue

**Comment by pheeria** [comment]
Sure, go ahead! I'll mark this as taken.

**Comment by br3akzero** [comment]
Awesome!

**Comment by br3akzero** [comment]
@pheeria, I tried to run the project yesterday and have failed miserably. The issue is that for some reason I am not able to install the dependencies for the project on my machine. I have tried with both `yarn` and `npm` but the same error persists, for some reason the package `slash` fails to install and throws an error. Can you please pull the master and try to install it on your machine and also it would be helpful if you could tell me your node and npm versions so that I could try installing the dependencies using those specific versions. 

Node versions tried: 
1. v13.6.0  | both yarn and npm ( LTS )
2. v14.8.0 | both yarn and npm ( LTS ) 
3. v15.0.1  | both yarn and npm ( LTS )

**Comment by pheeria** [comment]
@Denpex sorry to hear that. It works on my machine 🤷‍♂️ 
Also to fire up the project, you'd need to setup a firebase project (I'll add the info to the README soon).
What I'd suggest is to do the kebab-casing without starting the project for now and I'll pull the changes and check
whether everything still works. What do you think?

**Comment by br3akzero** [comment]
Sounds like a plan, I will send a pull request your way soon!
